In [281]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
import math
from math import log
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [320]:
#This is the result for testing between Physics and History apartment of UR. 
#The dataset has a total size of 99,
#while 24 is form History and 75 is from Physics.
#We chose 20 words that matters the most to form the dataset, 
#and label data from History as "1", data from Physics as "2".

In [321]:
#This is the part to do some basic process about the dataset. For the firt 24 rows, which is the data from history,
#add in a label "1". And for the following 75 rows, which is the data from Physics, add in a label "2".
#Then, to merge the two datasets (History + Physics) to get the final dataset.

In [395]:
smalltest = pd.read_csv("largetest 1.csv") #Import the dataset.
#smalltest.drop(index = 0, inplace=True)
smalltest = smalltest.drop('Unnamed: 0', axis = 1)
filt = smalltest.iloc[0:24] #Get the first 24 rows (data for History)
filt['output'] = [1 for row in range(len(filt))] #Add in a label "1" for the first 24 rows
filt2 = smalltest.iloc[24:99] #Get the next 75 rows (data for Physics)
filt2['output'] = [2 for row in range(len(filt2))] #Add in a label "2" for the next 75 rows
smalltest = pd.merge(filt, filt2, how = 'outer') #Merge the two datasets for History and Physics
smalltest

,physics,university,history,rochester,professor,research,matter,department,astronomy,quantum,...,optics,sciences,syllabushist,laser,energy,j,neutrino,plasma,graduate,output
0,-0.000000,-5.957578,-7.825721,-5.515152,-5.034577,-0.000000,-0.000000,-9.430149,-0.000000,-0.000000,...,-0.000000,-7.728905,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.000000,-7.166434,1
1,-0.000000,11.442468,37.055708,2.087719,-5.367759,-1.453511,-0.000000,-4.952153,-0.000000,-0.000000,...,-0.000000,-3.753147,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.000000,-5.116005,1
2,-0.000000,7.070112,37.593636,3.596986,-0.000000,0.277074,-0.000000,-1.279733,-0.000000,-0.000000,...,-0.000000,-1.612159,10.603996,-0.000000,-0.000000,-0.000000,-0.0,-0.000000,-1.107984,1
3,-0.000000,5.867648,71.824869,2.980578,-0.675768,0.667714,-0.000000,-0.499459,-0.000000,-0.000000,...,-0.000000,-0.811888,16.703638,-0.000000,-0.000000,-0.000000,-0.0,-0.000000,6.483429,1
4,-0.000000,12.123575,26.579184,22.884068,0.459068,-0.000000,-0.000000,5.589951,-0.000000,-0.000000,...,-0.000000,2.067702,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.000000,1.562095,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,28.228420,41.040154,0.000000,17.806931,4.794199,1.201978,6.259572,4.794199,4.794199,0.000000,...,0.000000,1.984424,0.000000,1.568811,1.568811,0.000000,0.0,1.568811,0.000000,2
95,74.941770,37.564294,-0.000000,15.597227,17.462182,0.540498,22.625715,2.370470,2.384010,0.547268,...,-0.000000,0.931768,-0.000000,0.730713,0.730713,-0.000000,-0.0,6.062091,-0.000000,2
96,35.237021,41.018891,0.000000,28.210788,8.813633,1.564662,12.913037,10.765774,4.786939,4.786939,...,0.000000,1.979757,0.000000,1.564662,1.564662,0.000000,0.0,1.564662,0.000000,2
97,45.323808,54.856189,-0.000000,14.181333,30.456432,33.505748,4.612710,22.181211,7.963272,-0.000000,...,6.513956,1.449195,-0.000000,1.142718,1.142718,-0.000000,-0.0,1.142718,-0.000000,2
98,51.279188,75.031276,0.000000,15.427512,33.354184,10.465010,11.225427,2.619172,2.619172,0.000000,...,0.000000,2.619172,0.000000,0.856669,0.856669,1.925004,0.0,0.856669,0.656252,2

In [382]:
filt

,physics,university,history,rochester,professor,research,matter,department,astronomy,quantum,...,optics,sciences,syllabushist,laser,energy,j,neutrino,plasma,graduate,output
0,-0.0,-5.957578,-7.825721,-5.515152,-5.034577,-0.000000,-0.000000,-9.430149,-0.0,-0.0,...,-0.0,-7.728905,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.0,-7.166434,1
1,-0.0,11.442468,37.055708,2.087719,-5.367759,-1.453511,-0.000000,-4.952153,-0.0,-0.0,...,-0.0,-3.753147,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.0,-5.116005,1
2,-0.0,7.070112,37.593636,3.596986,-0.000000,0.277074,-0.000000,-1.279733,-0.0,-0.0,...,-0.0,-1.612159,10.603996,-0.000000,-0.000000,-0.000000,-0.0,-0.0,-1.107984,1
3,-0.0,5.867648,71.824869,2.980578,-0.675768,0.667714,-0.000000,-0.499459,-0.0,-0.0,...,-0.0,-0.811888,16.703638,-0.000000,-0.000000,-0.000000,-0.0,-0.0,6.483429,1
4,-0.0,12.123575,26.579184,22.884068,0.459068,-0.000000,-0.000000,5.589951,-0.0,-0.0,...,-0.0,2.067702,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.0,1.562095,1
5,-0.0,28.692314,67.662217,9.512569,0.198109,5.078151,-0.000000,2.332443,-0.0,-0.0,...,-0.0,0.870882,1.675462,-0.000000,-0.000000,0.477353,-0.0,-0.0,11.091890,1
6,-0.0,24.091660,101.322904,4.497440,-0.163021,0.521601,-0.000000,0.677461,-0.0,-0.0,...,-0.0,0.874575,-0.141079,-0.000000,-0.000000,-0.000000,-0.0,-0.0,5.381753,1
7,-0.0,26.676196,26.676196,10.753850,-0.218527,0.873437,-0.000000,5.364106,-0.0,-0.0,...,-0.0,-0.272526,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.0,12.996055,1
8,-0.0,9.032517,28.475430,9.879921,-0.000000,4.755375,-0.000000,1.752552,-0.0,-0.0,...,-0.0,0.293307,19.226342,-0.000000,-0.000000,-0.000000,-0.0,-0.0,11.728627,1
9,-0.0,12.985136,226.829293,4.895596,0.085695,29.817270,0.181376,0.787764,-0.0,-0.0,...,-0.0,1.040652,5.511739,0.792577,-0.000000,0.085695,-0.0,-0.0,10.295949,1
10,-0.0,13.088524,27.978360,24.186749,-0.000000,-0.000000,-0.000000,6.265415,-0.0,-0.0,...,-0.0,2.476043,-0.000000,-0.000000,-0.000000,-0.000000,-0.0,-0.0,1.941993,1
11,-0.0,28.332136,162.978946,5.395789,-0.057080,0.463357,-0.033202,0.574737,-0.0,-0.0,...,-0.0,0.104768,8.661707,-0.000000,-0.000000,-0.000000,-0.0,-0.0,6.153732,1
12,-0.0,10.367532,41.140059,11.328783,-0.000000,1.684298,-0.000000,2.082517,-0.0,-0.0,...,-0.0,0.401261,21.914210,-0.000000,-0.000000,-0.000000,-0.0,-0.0,2.568421,1
13,-0.0,8.994195,110.198612,6.372635,0.835512,1.437517,-0.000000,1.664690,-0.0,-0.0,...,-0.0,1.918731,0.285091,-0.000000,-0.000000,-0.000000,-0.0,-0.0,7.386948,1
14,-0.0,9.076021,63.039129,15.019564,0.160134,0.436309,-0.000000,2.341633,-0.0,-0.0,...,-0.0,0.823518,4.121937,-0.000000,9.105423,-0.000000,-0.0,-0.0,0.619851,1
15,-0.0,15.997901,40.227460,25.939175,0.523661,-0.000000,-0.000000,4.516694,-0.0,-0.0,...,-0.0,1.806028,0.774735,-0.000000,-0.000000,-0.000000,-0.0,-0.0,1.423224,1
16,-0.0,22.707552,91.415104,22.707552,0.243989,1.764806,-0.000000,2.041429,-0.0,-0.0,...,-0.0,7.752259,0.358004,-0.000000,-0.000000,-0.000000,-0.0,-0.0,8.980354,1
17,-0.0,24.331504,85.489334,13.239969,0.265297,1.899074,-0.000000,2.195938,-0.0,-0.0,...,-0.0,0.888419,3.675999,-0.000000,-0.000000,-0.000000,-0.0,-0.0,2.540076,1
18,-0.0,16.992802,70.182782,8.538119,0.275986,26.094270,-0.000000,2.260506,-0.0,-0.0,...,-0.0,0.917468,42.597548,-0.000000,-0.000000,-0.000000,-0.0,-0.0,9.886434,1
19,-0.0,13.404222,37.465370,14.235410,0.285520,4.409976,-0.000000,5.379959,-0.0,-0.0,...,-0.0,0.955697,28.540992,-0.000000,-0.000000,-0.000000,-0.0,-0.0,22.880472,1
20,-0.0,24.449353,41.657903,8.385591,-0.000000,4.600750,-0.000000,2.231805,-0.0,-0.0,...,-0.0,0.911476,20.405761,-0.000000,-0.000000,-0.000000,-0.0,-0.0,14.979024,1
21,-0.0,7.976578,143.783155,7.976578,0.988300,2.758277,-0.000000,1.340029,-0.0,-0.0,...,-0.0,0.548947,8.964899,-0.000000,-0.000000,-0.000000,-0.0,-0.0,0.436644,1
22,-0.0,7.333465,132.000540,4.800108,0.219699,0.985790,-0.000000,1.140797,-0.0,-0.0,...,-0.0,0.400036,8.863214,-0.000000,-0.000000,0.143869,-0.0,-0.0,5.585301,1
23,-0.0,24.788862,98.081947,7.113258,-0.000000,10.718992,-0.000000,1.849972,-0.0,-0.0,...,-0.0,0.734722,5.613812,-0.000000,-0.000000,1.128553,-0.0,-0.0,8.226025,1

In [383]:
#This is the part to separate training set and testing set. I would pick a size of 10 as testing set, which includes
#5 data from History and 5 data from Physics.

In [396]:
#testing set
test_x = smalltest.iloc[21:31] #I would directly pick row 21 to row 30 a teting set.
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
test_x = np.array(test_x)
#training set
train_x_1 = smalltest.iloc[0:21] #The training set would then be row 0-20, and row 31-98. Merge then to get the training set.
train_x_2 = smalltest.iloc[31:99]
train_x = pd.merge(train_x_1, train_x_2, how = 'outer')
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)
train_x = np.array(train_x)
train_y = np.array(train_y)

In [397]:
test_y

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [398]:
#This is the part for SVM. We used the function .SVC directly since it's convenient and powerful.

In [399]:
#SVM
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [400]:
#For kernel function, we just pick "linear". We found out that the accuracy of linear function is already 100%,
#and we don't think we need to make the model more complicated by choosing another kernel function while linear function 
#can already work really well. For C, we just pick 100. We tried to test different C, like 0.01, 1, 100, 10000, but 
#there isn't much difference in the result. Therefore, we just picked 100.

In [401]:
lin = svm.SVC(kernel = 'linear', C = 100)
lin.fit(train_x, train_y)
predict = lin.predict(test_x)
acc_num = sum(predict == test_y)
acc_num

10

In [402]:
#This is the part to show final result. Predict shows the array of predicted result. 
#Accuracy show the percentage of accuracy.
#confusion_matrix would draw a confusion matrix which represents our result.

In [403]:
print("Predict:", predict)
print("Accuracy:" , acc_num/10)
confusion_matrix(test_y, predict)

Predict: [1 1 1 2 2 2 2 2 2 2]
Accuracy: 1.0

array([[3, 0],
       [0, 7]])