In [461]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
import math
from math import log
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [462]:
#This is the result for testing between Physics, History, and Computer Science apartment of UR. 
#The dataset has a total size of 144,
#while 24 is form History, 75 is from Physics, 45 is from Computer Sciecne.
#We chose 20 words that matters the most to form the dataset, 
#and label data from History as "1", data from Physics as "2", and data from Computer Science as "3".

In [463]:
#This is the part to do some basic process about the dataset. For the firt 24 rows, which is the data from history,
#add in a label "1". And for the following 75 rows, which is the data from Physics, add in a label "2".
#For the last 43 rows, which is the data from Computer Science, add in a label "3".
#Then, to merge the three datasets (History + Physics + Computer Science) to get the final dataset.

In [475]:
smalltest = pd.read_csv("UR3test.csv") #Import the dataset.
#smalltest.drop(index = 0, inplace=True)
smalltest = smalltest.drop('Unnamed: 0', axis = 1)
filt = smalltest.iloc[0:24] #Get the first 24 rows (data for History)
filt['output'] = [1 for row in range(len(filt))] #Add in a label "1" for the first 24 rows
filt2 = smalltest.iloc[24:99] #Get the next 75 rows (data for Physics)
filt2['output'] = [2 for row in range(len(filt2))] #Add in a label "2" for the next 75 rows
filt3 = smalltest.iloc[99:144] #Get the last 43 rows (data for Computer Science)
filt3['output'] = [3 for row in range(len(filt3))] #Add in a label "3" for the last 43 rows
smalltest = pd.merge(filt, filt2, how = 'outer') #Merge the three datasets for History, Physics, and Computer Science
smalltest = pd.merge(smalltest, filt3, how = 'outer')
smalltest

,physics,university,history,rochester,computer,professor,research,matter,m,science,...,astronomy,r,engineering,i,ieee,j,degrees,quantum,syllabushist,output
0,-0.0,-20.430556,-1.651042,-6.566840,-0.000000,-3.326823,-0.000000,-0.0,-0.000000,-0.000000,...,-0.0,-0.0,-0.664931,-0.000000,-0.0,-0.0,-0.000000,-0.0,-0.000000,1
1,-0.0,9.457948,49.435077,-0.773425,-0.000000,0.400064,18.207986,-0.0,-0.000000,-0.000000,...,-0.0,-0.0,-0.176698,11.740972,-0.0,-0.0,-0.000000,-0.0,-0.000000,1
2,-0.0,-6.800402,23.229353,-2.306836,-0.000000,-0.000000,3.815343,-0.0,0.210185,-0.000000,...,-0.0,-0.0,-0.234925,10.352811,-0.0,-0.0,-0.000000,-0.0,25.733333,1
3,-0.0,-4.176113,59.611018,-1.479342,-0.000000,-0.748052,2.492409,-0.0,-0.000000,-0.000000,...,-0.0,-0.0,-0.150580,45.941019,-0.0,-0.0,-0.000000,-0.0,30.334603,1
4,-0.0,-25.521187,-0.316836,-10.332894,-0.000000,-5.216407,-0.000000,-0.0,-0.000000,-0.000000,...,-0.0,-0.0,-1.051073,-0.000000,-0.0,-0.0,-0.000000,-0.0,-0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,-0.0,35.027219,-0.000000,20.083634,30.014285,-0.054304,0.134465,-0.0,-0.000000,14.867688,...,-0.0,-0.0,1.243309,-0.000000,-0.0,-0.0,4.754070,-0.0,-0.000000,3
140,-0.0,16.586714,-0.000000,21.106744,-0.000000,-0.056590,-0.000000,-0.0,-0.000000,3.682558,...,-0.0,-0.0,-0.000000,-0.000000,-0.0,-0.0,-0.000000,-0.0,-0.000000,3
141,-0.0,6.092107,-0.000000,10.237557,20.482909,-0.081527,-0.000000,-0.0,-0.000000,5.765575,...,-0.0,-0.0,2.182234,-0.000000,-0.0,-0.0,8.321882,-0.0,-0.000000,3
142,-0.0,6.163650,-0.000000,10.295687,20.528167,-0.074992,-0.000000,-0.0,-0.000000,5.795225,...,-0.0,-0.0,2.198016,-0.000000,-0.0,-0.0,8.353479,-0.0,-0.000000,3
143,-0.0,7.651830,-0.000000,12.706573,15.573110,-0.000000,-0.000000,-0.0,-0.000000,7.148580,...,-0.0,-0.0,2.716889,-0.000000,-0.0,-0.0,10.290616,-0.0,-0.000000,3

In [476]:
filt

,physics,university,history,rochester,computer,professor,research,matter,m,science,...,astronomy,r,engineering,i,ieee,j,degrees,quantum,syllabushist,output
0,-0.0,-20.430556,-1.651042,-6.566840,-0.000000,-3.326823,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.664931,-0.000000,-0.0,-0.000000,-0.0,-0.0,-0.000000,1
1,-0.0,9.457948,49.435077,-0.773425,-0.000000,0.400064,18.207986,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.176698,11.740972,-0.0,-0.000000,-0.0,-0.0,-0.000000,1
2,-0.0,-6.800402,23.229353,-2.306836,-0.000000,-0.000000,3.815343,-0.000000,0.210185,-0.000000,...,-0.0,-0.000000,-0.234925,10.352811,-0.0,-0.000000,-0.0,-0.0,25.733333,1
3,-0.0,-4.176113,59.611018,-1.479342,-0.000000,-0.748052,2.492409,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.150580,45.941019,-0.0,-0.000000,-0.0,-0.0,30.334603,1
4,-0.0,-25.521187,-0.316836,-10.332894,-0.000000,-5.216407,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-1.051073,-0.000000,-0.0,-0.000000,-0.0,-0.0,-0.000000,1
5,-0.0,0.512109,40.754809,-2.015619,-0.000000,-1.015869,3.479392,-0.000000,-0.000000,-0.263072,...,-0.0,-0.000000,-0.205262,0.564232,-0.0,0.404139,-0.0,-0.0,1.967209,1
6,-0.0,5.485966,81.825956,-1.114706,-0.000000,-0.560874,0.194752,-0.000000,-0.000000,-0.186928,...,-0.0,-0.000000,-0.113454,1.468268,-0.0,-0.000000,-0.0,-0.0,0.158499,1
7,-0.0,-3.967974,4.712671,-2.436682,-0.000000,-0.340035,0.463319,-0.000000,-0.000000,21.813947,...,-0.0,-0.000000,-0.247818,-0.077723,-0.0,-0.000000,-0.0,-0.0,-0.000000,1
8,-0.0,-5.486749,6.223454,-1.890415,-0.000000,-0.000000,3.421506,-0.000000,-0.000000,-0.224479,...,-0.0,-0.000000,-0.192170,42.354748,-0.0,-0.000000,-0.0,-0.0,21.647252,1
9,-0.0,2.368389,192.126219,-0.794176,2.429593,-0.254262,30.098104,-0.116233,-0.000000,-0.058271,...,-0.0,0.689700,-0.051221,98.256730,-0.0,0.024511,-0.0,-0.0,5.804652,1
10,-0.0,-24.072510,-2.322085,-10.139893,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-1.031822,-0.000000,-0.0,-0.000000,-0.0,-0.0,-0.000000,1
11,-0.0,12.167805,141.238690,-1.046992,-0.000000,-0.338930,0.189588,-0.171050,-0.000000,-0.000000,...,-0.0,-0.000000,-0.068054,2.638097,-0.0,-0.000000,-0.0,-0.0,10.786557,1
12,-0.0,-7.560170,15.132104,-2.714060,-0.000000,-0.000000,3.086921,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.276956,1.274934,-0.0,-0.000000,-0.0,-0.0,32.105188,1
13,-0.0,-2.706785,82.402782,-1.088613,-0.000000,-0.565066,1.264301,-0.000000,0.105430,0.439238,...,-0.0,-0.000000,-0.111041,4.823760,-0.0,-0.000000,-0.0,-0.0,0.197220,1
14,-0.0,-5.837517,37.469429,-3.273832,-0.000000,-1.077153,0.067778,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.216733,-0.000000,-0.0,-0.000000,-0.0,-0.0,5.769323,1
15,-0.0,-12.360769,12.535614,-6.944534,-0.000000,-2.291598,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.461621,-0.000000,-0.0,-0.000000,-0.0,-0.0,0.858894,1
16,-0.0,1.371811,55.272592,-0.218415,-0.000000,-0.597166,0.416938,-0.000000,79.657530,-0.000000,...,-0.0,-0.000000,-0.120494,-0.037589,-0.0,-0.000000,-0.0,-0.0,0.227499,1
17,-0.0,1.849092,57.724446,-2.256048,-0.000000,-0.745786,1.825169,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.150627,18.464334,-0.0,-0.000000,-0.0,-0.0,4.090317,1
18,-0.0,-1.440492,34.970746,-1.160552,-0.000000,-0.592478,21.323979,-0.000000,0.875768,-0.000000,...,-0.0,-0.000000,-0.119787,30.063512,-0.0,-0.000000,-0.0,-0.0,40.944045,1
19,-0.0,-2.621145,12.130078,-1.868173,-0.000000,-0.619674,3.983621,-0.000000,-0.000000,-0.000000,...,-0.0,1.206573,-0.125409,10.018677,-0.0,-0.000000,-0.0,-0.0,27.272398,1
20,-0.0,1.699911,15.313735,-1.125476,-0.000000,-0.000000,4.200371,-0.000000,-0.000000,0.672338,...,-0.0,-0.000000,-0.116316,20.902676,-0.0,-0.000000,-0.0,-0.0,19.338528,1
21,-0.0,-1.478574,116.299869,-1.182302,-0.000000,-0.276073,1.767906,-0.000000,0.084384,-0.000000,...,-0.0,-0.000000,-0.079790,-0.000000,-0.0,-0.000000,-0.0,-0.0,9.721529,1
22,-0.0,-1.690098,107.360287,-0.828625,-0.000000,-0.470117,0.411908,-0.000000,-0.000000,-0.088503,...,-0.0,-0.000000,-0.085732,6.986801,-0.0,0.104731,-0.0,-0.0,10.532420,1
23,-0.0,4.323743,71.420285,-1.198976,-0.000000,-0.000000,10.187943,-0.000000,-0.000000,-0.000000,...,-0.0,-0.000000,-0.123949,9.488598,-0.0,0.971539,-0.0,-0.0,6.634397,1

In [466]:
#This is the part to separate training set and testing set. I would pick a size of 15 as testing set, which includes
#5 data from History, 5 data from Physics, and 5 data from Computer Science.

In [477]:
#testing set
test_x_1 = smalltest.iloc[19:24] #I would directly pick row 19 to row 23 a testing set 1.
test_x_2 = smalltest.iloc[94:109] #I would directly pick row 94 to row 108 as testing set 2
test_x = pd.merge(test_x_1, test_x_2, how = 'outer')
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
test_x = np.array(test_x)
#training set
train_x_1 = smalltest.iloc[0:19] #The training set would then be row 0-18, row 24-93, and row 109-143. Merge then to get the training set.
train_x_2 = smalltest.iloc[24:94]
train_x_3 = smalltest.iloc[109:144]
train_x = pd.merge(train_x_1, train_x_2, how = 'outer')
train_x = pd.merge(train_x, train_x_3, how = 'outer')
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)
train_x = np.array(train_x)
train_y = np.array(train_y)

In [478]:
test_y

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [469]:
#This is the part for SVM. We used the function .SVC directly since it's convenient and powerful.

In [470]:
#SVM
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [471]:
#For kernel function, we just pick "linear". We found out that the accuracy of linear function is already 100%,
#and we don't think we need to make the model more complicated by choosing another kernel function while linear function 
#can already work really well. For C, we just pick 100. We tried to test different C, like 0.01, 1, 100, 10000, but 
#there isn't much difference in the result. Therefore, we just picked 100.

In [472]:
lin = svm.SVC(kernel = 'linear', C = 100)
lin.fit(train_x, train_y)
predict = lin.predict(test_x)
acc_num = sum(predict == test_y)
acc_num

19

In [473]:
#This is the part to show final result. Predict shows the array of predicted result. 
#Accuracy show the percentage of accuracy.
#confusion_matrix would draw a confusion matrix which represents our result.

In [474]:
print("Predict:", predict)
print("Accuracy:" , acc_num/20)
confusion_matrix(test_y, predict)

Predict: [1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 3 2]
Accuracy: 0.95

array([[5, 0, 0],
       [0, 5, 0],
       [0, 1, 9]])

In [ ]:
#I would like to explain this result, since there is one misprediction. 
#From the result it shows that a professor from CS department is predicted to be from Physics department. 
#However, after reading the dataset, we found that this professor has data really similar to professors in Physics department
#And after searching him on UR website, we found that he is both a Physics professor and a CS professor. 
#Therefore, I think it is reasonable that the result of our prediction is biased.