In [281]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
import math
from math import log
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [282]:
#This is the result for testing between Physics and History apartment of University of Buffalo. The dataset has a total size of 64,
#while 26 is form History and 38 is from Physics.
#We chose 20 words that matters the most to form the dataset, and label data from History as "1", data from Physics as "2".

In [283]:
#This is the part to do some basic process about the dataset. For the firt 26 rows, which is the data from history,
#add in a label "1". And for the following 38 rows, which is the data from Physics, add in a label "2".
#Then, to merge the two datasets (History + Physics) to get the final dataset.

In [305]:
smalltest = pd.read_csv("UBtest.csv") #Import the dataset.
#smalltest.drop(index = 0, inplace=True)
smalltest = smalltest.drop('Unnamed: 0', axis = 1)
filt = smalltest.iloc[0:26] #Get the first 26 rows (data for History)
filt['output'] = [1 for row in range(len(filt))] #Add in a label "1" for the first 26 rows
filt2 = smalltest.iloc[26:64] #Get the next 38 rows (data for Physics)
filt2['output'] = [2 for row in range(len(filt2))] #Add in a label "2" for the next 38 rows
smalltest = pd.merge(filt, filt2, how = 'outer') #Merge the two datasets for History and Physics
smalltest

,endnoindex,noindex,history,physics,war,disability,herzberg,latin,university,research,...,human,studies,world,j,drug,caraballo,rights,chile,ub,output
0,36.458656,33.135527,94.887658,0.000000,-0.038716,251.426648,0.0,0.000000,9.262585,0.767804,...,-0.002663,0.094004,0.000517,0.013285,0.0,-0.001298,-0.003540,0.0,0.000000,1
1,27.170645,24.689632,204.488581,0.000000,0.000000,0.482556,0.0,0.000000,2.830385,0.535814,...,0.000000,0.790984,0.000404,0.010029,0.0,-0.001080,0.000476,0.0,0.000000,1
2,200.969283,182.689168,-2.734801,0.000000,0.000000,-0.039118,0.0,11.018564,13.430191,1.413302,...,0.000000,4.555897,75.871280,0.064657,0.0,75.091013,-0.002673,0.0,1.119402,1
3,50.115829,45.513859,134.398678,0.000000,0.000000,-0.076957,0.0,0.000000,11.591763,0.974323,...,0.000000,-0.010690,0.000608,0.017428,0.0,-0.001483,0.000730,0.0,0.000000,1
4,42.181628,38.301627,154.673699,0.000000,-0.042271,-0.068383,0.0,0.000000,7.273164,0.594323,...,0.000000,0.000712,2.802291,-0.024219,0.0,-0.001309,0.000604,0.0,0.292289,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,203.013268,189.268357,0.000000,40.704211,0.000000,0.000000,0.0,0.000000,-0.003472,0.746469,...,0.000000,-0.001052,0.000000,0.000000,0.0,0.000000,-0.000147,0.0,2.572737,2
60,207.544311,193.589325,0.000000,12.609567,0.000000,0.000000,0.0,0.000000,0.035473,12.351685,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,-0.000149,0.0,4.183342,2
61,212.004556,197.847884,0.000000,12.783941,0.000000,0.000000,0.0,0.000000,0.039256,6.199652,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,-0.000151,0.0,2.792509,2
62,216.395110,202.044888,0.000000,13.563408,0.000000,0.000000,0.0,0.000000,0.043147,1.616554,...,0.000000,0.000000,0.000000,0.203291,0.0,0.000000,-0.000154,0.0,2.897618,2
63,220.717061,206.181182,0.000000,15.019515,0.000000,0.000000,0.0,0.000000,0.887651,13.244034,...,0.000000,-0.001033,0.000000,0.016739,0.0,0.000000,-0.000156,0.0,3.004092,2

In [285]:
#This is the part to separate training set and testing set. I would pick a size of 10 as testing set, which includes
#3 data from History and 7 data from Physics.

In [308]:
#testing set
test_x = smalltest.iloc[23:33] #I would directly pick row 23 to row 32 a teting set.
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
test_x = np.array(test_x)
#training set
train_x_1 = smalltest.iloc[0:23] #The training set would then be row 0-22, and row 33-63. Merge then to get the training set.
train_x_2 = smalltest.iloc[33:64]
train_x = pd.merge(train_x_1, train_x_2, how = 'outer')
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)
train_x = np.array(train_x)
train_y = np.array(train_y)

In [309]:
test_y

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [310]:
#This is the part for SVM. We used the function .SVC directly since it's convenient and powerful.

In [311]:
#SVM
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [312]:
#For kernel function, we just pick "linear". We found out that the accuracy of linear function is already 100%,
#and we don't think we need to make the model more complicated by choosing another kernel function while linear function 
#can already work really well. For C, we just pick 100. We tried to test different C, like 0.01, 1, 100, 10000, but 
#there isn't much difference in the result. Therefore, we just picked 100.

In [313]:
lin = svm.SVC(kernel = 'linear', C = 100)
lin.fit(train_x, train_y)
predict = lin.predict(test_x)
acc_num = sum(predict == test_y)
acc_num

10

In [314]:
#This is the part to show final result. Predict shows the array of predicted result. 
#Accuracy show the percentage of accuracy.
#confusion_matrix would draw a confusion matrix which represents our result.

In [315]:
print("Predict:", predict)
print("Accuracy:" , acc_num/10)
confusion_matrix(test_y, predict)

Predict: [1 1 1 2 2 2 2 2 2 2]
Accuracy: 1.0

array([[3, 0],
       [0, 7]])