In [15]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
import math
from math import log
import random
from random import randint
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
import math
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn import neighbors
warnings.filterwarnings("ignore")
%matplotlib inline

In [16]:
#This is the result for testing between Physics, History, and Computer Science apartment of four colleges
#UR, UB, VAN, MIT
#The dataset has a total size of 610,
#while 118 is form History, 270 is from Physics, 222 is from Computer Sciecne.
#We chose 20 words that matters the most to form the dataset, 
#and label data from History as "1", data from Physics as "2", and data from Computer Science as "3".

In [17]:
#This is the part to do some basic process about the dataset. For the firt 118 rows, which is the data from history,
#add in a label "1". And for the following 270 rows, which is the data from Physics, add in a label "2".
#For the last 222 rows, which is the data from Computer Science, add in a label "3".
#Then, to merge the three datasets (History + Physics + Computer Science) to get the final dataset.
smalltest = pd.read_csv("UR5test.csv") #Import the dataset.
smalltest = smalltest.drop('Unnamed: 0', axis = 1)
smalltest = smalltest.iloc[:, :20]
smalltest

,research,materials,engineering,science,chemical,quantum,ieee,degrees,fusion,optics,phys,award,matter,laser,journal,sciences,syllabushist,energy,laboratory,school
0,5.927908,-0.000000,-0.272432,3.880647,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,4.941213,-0.0,-0.000000,0.206064,1.076965,-0.000000,-0.000000,-0.000000,-0.132116
1,2.808217,-0.000000,-0.290219,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.074549,20.049505,-0.000000,-0.000000,-0.136805
2,0.131474,-0.000000,-0.202215,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.049161,25.392449,-0.000000,-0.000000,0.538984
3,2.179779,-0.000000,-0.219857,-0.185059,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,0.169117,-0.050424,1.459249,-0.000000,-0.000000,-0.095744
4,0.144611,-0.000000,-0.180695,-0.149694,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,0.942933,0.228682,-0.000000,-0.000000,-0.076228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,4.984081,1.697520,2.522020,-0.000000,19.214369,-0.0,0.534084,-0.0,-0.000000,-0.000000,-0.0,68.328206,-0.0,-0.000000,-0.000000,0.076785,-0.000000,0.404468,-0.000000,0.579441
198,1.384699,47.283175,0.394384,7.101051,13.760610,-0.0,-0.000000,-0.0,-0.000000,0.390071,-0.0,0.381177,-0.0,-0.000000,7.599991,0.055289,-0.000000,4.231391,0.419191,0.416157
199,1.352226,3.598881,1.762700,11.074256,98.607886,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,11.563601,-0.0,-0.000000,30.329245,0.054080,-0.000000,-0.000000,-0.000000,0.406055
200,-0.000000,-0.000000,30.663900,2.768896,9.265598,-0.0,-0.000000,-0.0,-0.000000,-0.000000,-0.0,0.685659,-0.0,-0.000000,-0.000000,0.098318,-0.000000,-0.000000,-0.000000,0.736429
201,4.586715,8.870927,4.414403,0.375562,6.761352,-0.0,-0.000000,-0.0,0.495983,-0.000000,-0.0,-0.000000,-0.0,4.343039,-0.000000,0.072064,-0.000000,2.332637,4.417190,2.349535

In [18]:
filt = smalltest.iloc[0:19] #Get the first 118 rows (data for History)
filt['output'] = [1 for row in range(len(filt))] #Add in a label "1" for the first 118 rows
filt2 = smalltest.iloc[19:92] #Get the next 270 rows (data for Physics)
filt2['output'] = [2 for row in range(len(filt2))] #Add in a label "2" for the next 270 rows
filt3 = smalltest.iloc[92:141] #Get the last 222 rows (data for Computer Science)
filt3['output'] = [3 for row in range(len(filt3))] #Add in a label "3" for the last 222 rows
filt4 = smalltest.iloc[141:181] #Get the last 222 rows (data for Computer Science)
filt4['output'] = [4 for row in range(len(filt4))] #Add in a label "3" for the last 222 rows
filt5 = smalltest.iloc[181:202] #Get the last 222 rows (data for Computer Science)
filt5['output'] = [5 for row in range(len(filt5))] #Add in a label "3" for the last 222 rows
smalltest = pd.merge(filt, filt2, how = 'outer') #Merge the three datasets for History, Physics, and Computer Science
smalltest = pd.merge(smalltest, filt3, how = 'outer')
smalltest = pd.merge(smalltest, filt4, how = 'outer')
smalltest = pd.merge(smalltest, filt5, how = 'outer')
smalltest

,research,materials,engineering,science,chemical,quantum,ieee,degrees,fusion,optics,...,award,matter,laser,journal,sciences,syllabushist,energy,laboratory,school,output
0,5.927908,-0.000000,-0.272432,3.880647,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,4.941213,-0.0,-0.000000,0.206064,1.076965,-0.000000,-0.000000,-0.000000,-0.132116,1
1,2.808217,-0.000000,-0.290219,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,-0.000000,-0.0,-0.000000,-0.000000,-0.074549,20.049505,-0.000000,-0.000000,-0.136805,1
2,0.131474,-0.000000,-0.202215,-0.000000,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,-0.000000,-0.0,-0.000000,-0.000000,-0.049161,25.392449,-0.000000,-0.000000,0.538984,1
3,2.179779,-0.000000,-0.219857,-0.185059,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,-0.000000,-0.0,-0.000000,0.169117,-0.050424,1.459249,-0.000000,-0.000000,-0.095744,1
4,0.144611,-0.000000,-0.180695,-0.149694,-0.000000,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,-0.000000,-0.0,-0.000000,-0.000000,0.942933,0.228682,-0.000000,-0.000000,-0.076228,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,4.984081,1.697520,2.522020,-0.000000,19.214369,-0.0,0.534084,-0.0,-0.000000,-0.000000,...,68.328206,-0.0,-0.000000,-0.000000,0.076785,-0.000000,0.404468,-0.000000,0.579441,5
198,1.384699,47.283175,0.394384,7.101051,13.760610,-0.0,-0.000000,-0.0,-0.000000,0.390071,...,0.381177,-0.0,-0.000000,7.599991,0.055289,-0.000000,4.231391,0.419191,0.416157,5
199,1.352226,3.598881,1.762700,11.074256,98.607886,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,11.563601,-0.0,-0.000000,30.329245,0.054080,-0.000000,-0.000000,-0.000000,0.406055,5
200,-0.000000,-0.000000,30.663900,2.768896,9.265598,-0.0,-0.000000,-0.0,-0.000000,-0.000000,...,0.685659,-0.0,-0.000000,-0.000000,0.098318,-0.000000,-0.000000,-0.000000,0.736429,5
201,4.586715,8.870927,4.414403,0.375562,6.761352,-0.0,-0.000000,-0.0,0.495983,-0.000000,...,-0.000000,-0.0,4.343039,-0.000000,0.072064,-0.000000,2.332637,4.417190,2.349535,5

In [19]:
#This is the part to separate training set and testing set. I would pick a size of 15 as testing set, which includes
#5 data from History, 5 data from Physics, and 5 data from Computer Science.

In [20]:
answer = []
count = 0
for i in range(100):
    smalltest_new = pd.merge(filt, filt2, how = 'outer') #Merge the three datasets for History, Physics, and Computer Science
    smalltest_new = pd.merge(smalltest_new, filt3, how = 'outer')
    smalltest_new = pd.merge(smalltest_new, filt4, how = 'outer')
    smalltest_new = pd.merge(smalltest_new, filt5, how = 'outer')
    loc_1 = random.randint(0, 10)
    loc_2 = random.randint(19, 60)
    loc_3 = random.randint(92,120)
    loc_4 = random.randint(141,160)
    loc_5 = random.randint(181,185)
    #print("loc_1: ", loc_1)
    #print("loc_2: ", loc_2)
    #print("loc_3: ", loc_3)

    test_x = smalltest_new.iloc[[loc_1, loc_1+3, loc_1+6, loc_1+9, loc_1+12, loc_2, loc_2+3, loc_2+6, loc_2+9, loc_2+12, loc_3, loc_3+3, loc_3+6, loc_3+9, loc_3+12, loc_4, loc_4+3, loc_4+6, loc_4+9, loc_4+12, loc_5, loc_5+3, loc_5+6, loc_5+9, loc_5+12], :]
    train_x = smalltest_new.drop([loc_1, loc_1+3, loc_1+6, loc_1+9, loc_1+12, loc_2, loc_2+3, loc_2+6, loc_2+9, loc_2+12, loc_3, loc_3+3, loc_3+6, loc_3+9, loc_3+12, loc_4, loc_4+3, loc_4+6, loc_4+9, loc_4+12, loc_5, loc_5+3, loc_5+6, loc_5+9, loc_5+12])
    test_y = np.array(test_x['output'])
    test_x = test_x.drop('output', axis = 1)
    train_y = np.array(train_x['output'])
    train_x = train_x.drop('output', axis = 1)
    
    lin = svm.SVC(kernel = 'rbf', C = 100)
    lin.fit(train_x, train_y)
    predict = lin.predict(test_x)
    
    #knn = neighbors.KNeighborsRegressor(14, weights="uniform")
    #knn.fit(np.array(train_x), np.array(train_y))
    #predict = knn.predict(test_x)
    
    acc_num = sum(predict == test_y)
    answer.append(acc_num)

accuracy = np.average(answer)

print("accuracy:", accuracy)

accuracy: 17.45

In [6]:
loc_1 = random.randint(0, 160)
loc_2 = random.randint(170, 440)
loc_3 = random.randint(450,750)
print("loc_1: ", loc_1)
print("loc_2: ", loc_2)
print("loc_3: ", loc_3)

test_x = smalltest.iloc[[loc_1, loc_1+3, loc_1+6, loc_1+9, loc_1+12, loc_2, loc_2+3, loc_2+6, loc_2+9, loc_2+12, loc_3, loc_3+3, loc_3+6, loc_3+9, loc_3+12], :]
train_x = smalltest.drop([loc_1, loc_1+3, loc_1+6, loc_1+9, loc_1+12, loc_2, loc_2+3, loc_2+6, loc_2+9, loc_2+12, loc_3, loc_3+3, loc_3+6, loc_3+9, loc_3+12])
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)

loc_1:  59
loc_2:  431
loc_3:  555

In [409]:
'''
#testing set
test_x_1 = smalltest.iloc[113:118] #I would directly pick row 21 to row 25 a testing set 1.
test_x_2 = smalltest.iloc[383:393] #I would directly pick row 140 to row 149 as testing set 2
test_x = pd.merge(test_x_1, test_x_2, how = 'outer')
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
test_x = np.array(test_x)
#training set
train_x_1 = smalltest.iloc[0:113] #The training set would then be row 0-20, row 26-139, and row 150-215. Merge then to get the training set.
train_x_2 = smalltest.iloc[118:383]
train_x_3 = smalltest.iloc[393:610]
train_x = pd.merge(train_x_1, train_x_2, how = 'outer')
train_x = pd.merge(train_x, train_x_3, how = 'outer')
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)
train_x = np.array(train_x)
train_y = np.array(train_y)
'''

"\n#testing set\ntest_x_1 = smalltest.iloc[113:118] #I would directly pick row 21 to row 25 a testing set 1.\ntest_x_2 = smalltest.iloc[383:393] #I would directly pick row 140 to row 149 as testing set 2\ntest_x = pd.merge(test_x_1, test_x_2, how = 'outer')\ntest_y = np.array(test_x['output'])\ntest_x = test_x.drop('output', axis = 1)\ntest_x = np.array(test_x)\n#training set\ntrain_x_1 = smalltest.iloc[0:113] #The training set would then be row 0-20, row 26-139, and row 150-215. Merge then to get the training set.\ntrain_x_2 = smalltest.iloc[118:383]\ntrain_x_3 = smalltest.iloc[393:610]\ntrain_x = pd.merge(train_x_1, train_x_2, how = 'outer')\ntrain_x = pd.merge(train_x, train_x_3, how = 'outer')\ntrain_y = np.array(train_x['output'])\ntrain_x = train_x.drop('output', axis = 1)\ntrain_x = np.array(train_x)\ntrain_y = np.array(train_y)\n"

In [7]:
test_y

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [317]:
#This is the part for SVM. We used the function .SVC directly since it's convenient and powerful.

In [318]:
#SVM
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [319]:
#For kernel function, we just pick "linear". We found out that the accuracy of linear function is already 100%,
#and we don't think we need to make the model more complicated by choosing another kernel function while linear function 
#can already work really well. For C, we just pick 100. We tried to test different C, like 0.01, 1, 100, 10000, but 
#there isn't much difference in the result. Therefore, we just picked 100.

In [320]:
lin = svm.SVC(kernel = 'rbf', C = 100)
lin.fit(train_x, train_y)
predict = lin.predict(test_x)
acc_num = sum(predict == test_y)
acc_num

11

In [321]:
#This is the part to show final result. Predict shows the array of predicted result. 
#Accuracy show the percentage of accuracy.
#confusion_matrix would draw a confusion matrix which represents our result.

In [322]:
print("Predict:", predict)
print("Accuracy:" , acc_num/15)
confusion_matrix(test_y, predict)

Predict: [2 1 1 1 1 2 2 2 2 2 2 3 2 2 3]
Accuracy: 0.7333333333333333

array([[4, 1, 0],
       [0, 5, 0],
       [0, 3, 2]])

In [13]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

x = tf.placeholder(tf.float32, [None, 20])

W = tf.Variable(tf.zeros([20, 3]))

b = tf.Variable(tf.zeros([3]))

y = tf.nn.softmax(tf.matmul(x, W) + b)

y_ = tf.placeholder(tf.float32, [None, 3])

cross_entropy = -tf.reduce_sum(y_ * tf.log(y + 1e-10))

train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

# 初始化
init = tf.initialize_all_variables()

# Session
sess = tf.Session()
sess.run(init)

# 迭代
for i in range(1000):
    sess.run(train_step, feed_dict={x: train_x, y_: train_y})
    if i % 50 == 0:
        correct_prediction = tf.equal(test_x, test_y)
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

WARNING:tensorflow:From /Users/runzhouliu/Desktop/anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /Users/runzhouliu/Desktop/anaconda3/lib/python3.8/site-packages/tensorflow/python/util/tf_should_use.py:247: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

ValueError: Cannot feed value of shape (737,) for Tensor 'Placeholder_1:0', which has shape '(?, 3)'

In [36]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(64,activation='relu',input_shape=(20,)))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(46,activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history =  model.fit(train_x,
                  train_y,
                  epochs=8,
                  batch_size=512)
results = model.evaluate(test_x,test_y)
print(results)

Train on 737 samples
Epoch 1/8
737/737 [==============================] - 0s 86us/sample - loss: 8.4207 - acc: 0.0027
Epoch 2/8
737/737 [==============================] - 0s 6us/sample - loss: 4.5146 - acc: 0.0556
Epoch 3/8
737/737 [==============================] - 0s 6us/sample - loss: 2.7123 - acc: 0.2768
Epoch 4/8
737/737 [==============================] - 0s 5us/sample - loss: 1.9477 - acc: 0.5360
Epoch 5/8
737/737 [==============================] - 0s 7us/sample - loss: 1.6097 - acc: 0.7436
Epoch 6/8
737/737 [==============================] - 0s 5us/sample - loss: 1.4329 - acc: 0.7680
Epoch 7/8
737/737 [==============================] - 0s 6us/sample - loss: 1.3097 - acc: 0.8060
Epoch 8/8
737/737 [==============================] - 0s 7us/sample - loss: 1.2188 - acc: 0.8277
[1.2273503541946411, 0.73333335]